[package]
name = "unboxit-json"
version = "0.1.0"

edition.workspace = true
license.workspace = true

[dependencies]
unboxit = { version = "0.1.0", path = "../unboxit-core" }
unboxit-derive = { version = "0.1.0", path = "../unboxit-derive" }
